### ISSUE TITLE
Suggest rename api-overview to overview/ in templates/

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#27]
We have created api specific template directories in the templates/ directory:
api-overview/
api-quickstart/
api-reference/

I think we should be making these generic and not tieing ourselves to docs about APIs. Ie, rename templates to. At a later stage, we might decide we need a specific API instance, but I think we should start generic. 
overview/
quickstart/
reference/

**Comment by jaredmorgs** [comment]
The problem is that we can't. At least with the proposed templates as they are.

@cwcromwell would need to rework the templates to make them generic.

I agree that the guidance provided in them is excellent and would be a great universal guide if the focus on APIs could be removed.

I would actually fork each of these directories into the suggested ones, then sanitise them (make them applicable to all of the doc types suggested by the folder names).

**Comment by camerons** [comment]
I'm closing out this task. We haven't addressed it for 0.1 release, and I expect it to be captured in the total overview for future releases.
