### ISSUE TITLE
Term "linter" not understood

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/templates#66]
Document: https://github.com/thegooddocsproject/templates/blob/master/writing-tips.md

Re:

> Run your text through a grammar **linter** to check how readable it is.
> Tools like Grammarly help you identify grammar issues
> Tools like Vale help you identify style issues.

Felicity Brand
13:34 14 Nov
First time I've ever come across this word. Might not translate well?

Josh Sherwood
13:36 14 Nov
Agreed ++

Louise Brooks
13:41 14 Nov
linter? what's that?!

Josh Sherwood
13:30 14 Nov
Include links to these tools?

**Comment by bjnath** [comment]
> First time I've ever come across this word. Might not translate well?

Perhaps we can link the word to [its Wikipedia article](https://en.wikipedia.org/wiki/Lint_(software)). That not only will gloss it, it will make the definition available in multiple languages.

I'd hesitate to drop it, because it connects with developer experience and the metaphor is witty. (And, unlike humor generally, it'll stay witty to those who need to look it up.)

**Comment by jaredmorgs** [comment]
I agree this is the correct approach. Particularly as we list two grammar linters directly below the offending line.

**Comment by shreyas1599** [comment]
@camerons I think this issue can be closed. Looks like #109 fixed it.

**Comment by jaredmorgs** [comment]
Closing
